### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by oliveiralberto** [flybywiresim/msfs-blender-tools#1]
### Feature Description

Installation guide please! or some instruction on the description. 

I used previous versions without much news. but new version was impossible for me to install. I see it in the addons manager but I can't configure it. despite starting blender as administrator it doesn't download what I need. any suggestion?

blender version 3.1

### Anything else?

![Captura de pantalla (3309)](https://user-images.githubusercontent.com/70357882/160477603-1d9f3d7b-172c-4528-92a4-0074dfe4f6c2.png)

**Comment by pepperoni505** [comment]
Hi,

Thank you for your interest in this addon. This is still VERY early into development, and is not intended to be used at its current state. There are many bugs with the installation process that will be ironed out. Please do not hesitate to reopen this issue if you are experiencing the same issues after our initial release.
